# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: '0 * * * *'  # Запуск каждый час
  
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # Клонируем репозиторий

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt


      - name: Run Scraper
        run: python parse.py  # Запуск скрипта


      - name: Commit and Push results
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          
          if [ -f products.json ]; then
            git add products.json
            git commit -m "Update products.json" || echo "No changes to commit"
      
            # Добавляем токен для аутентификации
            git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/Aleknew/yushkoff.git
            git push
          else
            echo "Файл products.json не найден, пропускаем коммит."
          fi

